# Generated by Django 2.0.8 on 2018-11-11 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GuestEnail',
            new_name='GuestEmail',
        ),
    ]
