# Generated by Django 2.0.8 on 2018-09-18 05:39

from django.db import migrations, models
import product1.models


class Migration(migrations.Migration):

    dependencies = [
        ('product1', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=product1.models.upload_image_path),
        ),
    ]
