# Generated by Django 2.0.8 on 2018-09-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product1', '0003_auto_20180918_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
